on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get latest release tag
        run: |
          echo $(git tag)
          echo $(git tag --sort=-v:refname -l dawn/\*)
          echo $(git tag --sort=-v:refname -l dawn/\* | head -c 1)
          TAG_NAME=$(git tag --sort=-v:refname -l dawn/\* | head -c 1)
          echo "TAG_NAME=$TAG_NAME"
