on:
  workflow_call:
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest tag
        id: find-tag
        run: |
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV | head -n 1 | tail -c +11 > tag-name
          echo "tag-name=$(cat tag-name)" >> "$GITHUB_OUTPUT"

  build-artifacts:
    strategy:
      matrix:
        os:
          - name: linux
            image: ubuntu-latest
          - name: windows
            image: windows-latest
          - name: macos
            image: macos-latest
        config: [ Debug, Release ]

    runs-on: ${{ matrix.os.image }}
    needs: prebuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prebuild.steps.find-tag.outputs.tag-name }}

      - name: Configure
        run: >
          cmake
          -B out
          -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DCMAKE_INSTALL_PREFIX=out/install

      - name: Build
        run: >
          cmake
          --build out
          --config ${{ matrix.config }}

      - name: Install
        run: >
          cmake
          --install out
          --config ${{ matrix.config }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dawn-${{ matrix.os.name }}-x64-${{ matrix.config }}
          path: |
            out/install

