on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest tag
        run: |
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\*
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -V
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -V | head -c 1
          TAG_NAME=$(git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -V | head -c 1)
          echo "TAG_NAME=$TAG_NAME"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get latest release tag
        run: |
          cd $GITHUB_WORKSPACE
          git show-ref
          #echo $(git tag)
          #echo $(git tag --sort=-v:refname -l dawn/\*)
          #echo $(git tag --sort=-v:refname -l dawn/\* | head -c 1)
          #TAG_NAME=$(git tag --sort=-v:refname -l dawn/\* | head -c 1)
          #echo "TAG_NAME=$TAG_NAME"
