on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest tag
        id: find-tag
        run: |
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV | head -n 1 | tail -c +11 > /tmp/tag-name
          echo "tag-name=$(cat /tmp/tag-name)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.find-tag.outputs.tag-name }}

      - name: Configure
        run: >
          cmake
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=install

      - name: Build
        run: >
          cmake
          --build build
          --config Release

      - name: Install
        run: >
          cmake
          --install build
          --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dawn-linux-x64-release
          path: |
            build/install

