on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get latest release tag
        run: |
          cd $GITHUB_WORKSPACE
          git tag
