on:
  create:
  workflow_dispatch:

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Build artifacts
        run: echo "This builds artifacts for ref ${{ github.ref_name }} (${{ github.ref }})."

