on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest tag
        id: find-tag
        run: |
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\*
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV | head -n 1
          git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV | head -n 1 | tail -c +11
          export TAG_NAME=$(git ls-remote --tags https://github.com/${GITHUB_REPOSITORY}.git dawn/\* | cut -f2 | sort -rV | head -c 1 | tail -c +11)
          echo "TAG_NAME=$TAG_NAME"
          echo "tag-name=$TAG_NAME" >> "$GITHUB_OUTPUT"
      - name: Test output
        run: echo "CHECK_TAG_NAME=$TAG_NAME"
        env:
          TAG_NAME: ${{ steps.find-tag.outputs.tag-name }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.find-tag.outputs.tag-name }}
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          git status
