on:
  schedule:
    - cron: '20 5,17 * * *'
  workflow_dispatch:

env:
  UPSTREAM_REMOTE: https://github.com/eliemichel/Dawn-mock

jobs:
  sync_mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Merge from '${{ env.UPSTREAM_REMOTE }}'
        run: |
          echo "This merges upstream repo"
          # Inspired by https://github.com/bridgelightcloud/github-mirror-action/blob/main/action.sh
          git config --global --add safe.directory /github/workspace
          git clone --bare "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          git remote add --mirror=fetch upstream "${{ env.UPSTREAM_REMOTE }}"
          git fetch upstream +refs/heads/*:refs/remotes/origin/*
          echo "Pushing to 'https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git'..."
          git push --mirror --prune "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
